package ZoomerScript.sandbox;

/*Generated by MPS */


public class Scratch {
  public Scratch() {
  }
  public static void main(String[] args) {
    System.out.println("Starting main in " + "Scratch" + "...");
    // Start of file

    // Variables
    double number1 = 2;
    number1 = 10;
    double number2 = 13;
    boolean fo_sure = true;

    // Arithmetics and logic
    System.out.println(number1);
    if (fo_sure) {
      number1 = number1 + 5;
      System.out.println(number1);
      number1 = number1 - 10;
      System.out.println(number1);
      number1 = number1 * 20;
      System.out.println(number1);
      number1 = number1 / 13;
      System.out.println(number1);
    }

    boolean canYouSeeMe = false;
    System.out.println(canYouSeeMe);
    if (false) {
      canYouSeeMe = false;
    } else {
      canYouSeeMe = true;
    }
    System.out.println(canYouSeeMe);
    // End of file
    System.out.println("Exiting main in " + "Scratch" + "...");
  }
}
