package ZoomerScript.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBehaviorAspectDescriptor;
import jetbrains.mps.core.aspects.behaviour.api.BHDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public final class BehaviorAspectDescriptor extends BaseBehaviorAspectDescriptor {
  private final BHDescriptor myScript__BehaviorDescriptor = new Script__BehaviorDescriptor();
  private final BHDescriptor myIf__BehaviorDescriptor = new If__BehaviorDescriptor();
  private final BHDescriptor myComment__BehaviorDescriptor = new Comment__BehaviorDescriptor();

  public BehaviorAspectDescriptor() {
  }

  @Nullable
  public BHDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return myComment__BehaviorDescriptor;
      case 1:
        return myIf__BehaviorDescriptor;
      case 2:
        return myScript__BehaviorDescriptor;
      default:
    }
    return null;
  }
  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x7cb4518a20f54c01L, 0x8fe1dda960632cd1L, 0x73080c70fb099a8dL), MetaIdFactory.conceptId(0x7cb4518a20f54c01L, 0x8fe1dda960632cd1L, 0x73080c70fb00921eL), MetaIdFactory.conceptId(0x7cb4518a20f54c01L, 0x8fe1dda960632cd1L, 0x73080c70faf36806L)).seal();
}
