package ZoomerScript.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;

public class EmptyLine_SubstituteMenu extends SubstituteMenuBase {
  public EmptyLine_SubstituteMenu() {
    super(false, new EditorMenuDescriptorBase("default substitute menu for " + "EmptyLine", new SNodePointer("r:093c087b-a592-41b9-a09a-1a8b5ffd6af5(ZoomerScript.editor)", "8288888793563115792")));
  }

}
